## The code in the functions below is intended to demonstrate some useful
## features of lexical scoping by caching an inverted matrix to avoid unecessarily repeating
## the compute intensive operation of matrix inversion.  

## The makeCacheMatrix function makes a list available in the parent environment which provides
## cacheSolve with information it needs to produce the inverse of a matrix by first attempting to 
## retrieve it from a cache and, failing that, to compute it using the solve() function

makeCacheMatrix <- function(x = matrix()) {
  i <- NULL
  set <- function(y) {
    x <<- y
    i <<- NULL
  }
  get <- function() x
  setinverse <- function(inverse) i <<- inverse
  getinverse <- function() i
  list(set = set,
       get = get,
       setinverse = setinverse,
       getinverse = getinverse)
}

## The cacheSolve function uses information generated by makeCacheMatrix to:
## 
## 1 - determine if the cached inverse exists  (depending on the value of x$getinverse)
## 2 - retrieve cached inverse if it does exist in the cache
## 3 - calculate the inverse by using the solve() function if the cached inverse does not exist

cacheSolve <- function(x, ...) {
  i <- x$getinverse()
  if (!is.null(i)) {
    message("getting cached data")
    return(i)
  }
  data <- x$get()
  i <- solve(data, ...)
  x$setinverse(i)
  i
}